name: CD Workflow

on:
  push:
    branches: 
      - 'master'

jobs:
  cd-deploy-test: 
    name: Deploy to tests
    runs-on: ubuntu-latest
    environment: 
      name: adt_test

    steps:     
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with :
        python-version: '3.12.3'
    
    - name: Install Databricks CLI
      run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure Databricks
      run: |
        # write out the profile (here called "ADT_TEST")
        cat <<EOF > ~/.databrickscfg
        [TEST]
        host = https://adb-3219440406780807.7.azuredatabricks.net
        azure_tenant_id = ${{secrets.AZURE_TENANT_ID }}
        azure_client_id = ${{secrets.AZURE_CLIENT_ID }}
        azure_client_secret = ${{secrets.AZURE_CLIENT_SECRET }}
        EOF

    - name: Deploy to ADT_TEST
      run: |
        databricks bundle deploy \
          --target test \
          --profile TEST
